imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

    
mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~

## REFERENCE ##
#mobile_detect:
#    redirect:
#        mobile:
#            is_enabled: true            # default false
#            host: http://m.site.com     # with scheme (http|https), default null, url validate
#            status_code: 301            # default 302
#            action: redirect            # redirect, no_redirect, redirect_without_path 
#        tablet:
#            is_enabled: true            # default false
#            host: http://t.site.com     # with scheme (http|https), default null, url validate
#            status_code: 301            # default 302
#            action: redirect            # redirect, no_redirect, redirect_without_path 
#    switch_device_view:
#        save_referer_path: false        # default true
                                        # true  redirectUrl = http://site.com/current/path
                                        # false redirectUrl = http://site.com  
                                        
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: TechG\AuthProjectBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address:        noreply@e-menu.com
        sender_name:    E-menu
    profile:
        form:
            type:               tech_g_auth_project_user_profile      
    registration:
        form:
            type:               tech_g_auth_project_user_registration
            handler:            tech_g_auth_project.form.handler.registration                     
        confirmation:
            enabled:    true
            from_email:
                address:        registration@sts.com
                sender_name:    AuthProjectBundle Registration
            template:   FOSUserBundle:Registration:confirmation.email.html.twig
    resetting:
        email:
            from_email:
                address:        resetting@sts.com
                sender_name:    AuthProjectBundle Resetting                
            template:   FOSUserBundle:Registration:resetting.email.html.twig        

#avalanche_imagine:
#    filters:
#        my_thumb:
#            type:    thumbnail
#            options: { size: [120, 90], mode: outbound, quality: 100, format: png }

                                        