tech_g_auth_project:
    resource: "@TechGAuthProjectBundle/Resources/config/routing.yml"
    prefix:   /

tech_g_base_project:
    resource: "@TechGBaseProjectBundle/Resources/config/routing.yml"
    prefix:   /
